\c template_postgis

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS ltree;

CREATE USER cerezo WITH CREATEDB PASSWORD 'cerezo';

CREATE DATABASE cerezo_master WITH OWNER = cerezo TEMPLATE = template_postgis;
